// constands used in sketch
#define OPTION_SETTINGS_UNUSED 0
#define OPTION_SETTINGS_WINDOW 1
#define OPTION_SETTINGS_SHUTTER 2
#define OPTION_SETTINGS_SAMEAS1 3
#define OPTION_SETTINGS_SAMEAS2 4

#define OPTION_LOCK_ACTION_NONE 0
#define OPTION_LOCK_ACTION_OPEN 1
#define OPTION_LOCK_ACTION_CLOSE 2

#define OPTION_UNLOCK_ACTION_NONE 0
#define OPTION_UNLOCK_ACTION_OPEN 1
#define OPTION_UNLOCK_ACTION_CLOSE 2
#define OPTION_UNLOCK_ACTION_PREVIOUS_POS 3

